#' Table imputation methods
#' 
#' Replace missing value methods with a variety of methods 
#' 
#' @param .tbl table-like or list-like structure
#' @param .vars list of columns generated by vars(), or a character vector of 
#'        column names, or a numeric vector of column positions.
#' @param .predicate A predicate function to be applied to the columns or a 
#'         logical vector. 
#' @param ... addition passed to the imputation method
#' 
#' @details 
#' 
#' These methods are modelled closely after [dplyr::mutate()] and related 
#' functions 
#' 
#' @examples 
#' 
#'   nacars %>% impute_zero() 
#'   nacars %>% impute_zero( mpg, cyl )
#'   nacars %>% impute_zero( "mpg", "cyl" )
#'   nacars %>% impute_zero( c("mpg","cyl") )
#'   nacars %>% impute_zero( 1:2 )
#'   
#' @md

#' @rdname impute
#' @export
impute_zero <- function(.tbl, ...) na_replace(.tbl, .na=na.zero, ... )

#' @rdname impute
#' @export
impute_zero_at <- function( .tbl, .vars, ...) na_replace_at( .tbl, .na=na.zero, .vars )

#' @rdname impute
#' @export
impute_zero_all <- function( .tbl, ... ) na_replace_all( .tbl, .na=na.zero, ...  )

#' @rdname impute
#' @export
impute_zero_if <- function( .tbl, .na, .predicate, ... ) na_replace_if( .tbl, .na=na.zero, .predicate, ...  )


#' @examples 
#' 
#'   nacars %>% impute_inf() 
#'   nacars %>% impute_inf( mpg, cyl )
#'   nacars %>% impute_inf( "mpg", "cyl" )
#'   nacars %>% impute_inf( c("mpg","cyl") )
#'   nacars %>% impute_inf( 1:2 )
#'   
#' @rdname impute
#' @export
impute_inf <- function(.tbl, ...) na_replace(.tbl, .na=na.inf, ... )

#' @rdname impute
#' @export
impute_inf_at <- function( .tbl, .vars, ...) na_replace_at( .tbl, .na=na.inf, .vars )

#' @rdname impute
#' @export
impute_inf_all <- function( .tbl, ... ) na_replace_all( .tbl, .na=na.inf, ...  )

#' @rdname impute
#' @export
impute_inf_if <- function( .tbl, .na, .predicate, ... ) na_replace_if( .tbl, .na=na.inf, .predicate, ...  )





# impute_mean <- function(.tbl,  ...) na_replace( .tbl, .na=na.mean, ... 
# na_zero <- function(.tbl, ...) na_replace(.tbl, .na=na.zero, ... )
# na_zero_at <- function( .tbl, .vars, ...) na_replace_at( .tbl, .na=na.zero, .vars )
# na_zero_all <- function( .tbl, ... ) na_replace_all( .tbl, .na=na.zero, ...  )
# na_zero_if <- function( .tbl, .na, .predicate, ... ) na_replace_if( .tbl, .na=na.zero, .predicate, ...  )
# 



#' 
#'   
#' #' @rdname na-tables 
#' #' @export
#' na_inf <- mk_recursive(na.inf)
#' 
#' #' @rdname na-tables 
#' #' @export
#' na_neginf <- mk_recursive(na.neginf)